import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:4000" }),
  endpoints: (builder) => ({
    getNotes: builder.query({
      // baseUrl + '/notes'
      query: () => "/notes",
    }),
  }),
});

// useGetNotesQuery is autogenerated from 'getNotes'
export const { useGetNotesQuery } = apiSlice;
